development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: rails-chat-tutorial_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: rails-chat-tutorial_production
